# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NTdmMzUxZjdlYjg3NzI5ZWU1ODkyMDgwYmUxZDFjYmFkMTcwNGE3ZGJjYTM3ZDYzYjgyODg0M2JmOWVkYTc4NTNhYzM3Njk5NmU3MjhkZDM2M2VkMGEwYjlmMzcwNzdmZTgxN2FmYTBhNWMzNzY2ZmQ5NmI0NDI5NmYyMjY0ZmU=
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: jojoaddison
    password:
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: jojoaddison
    password:
