export enum Market {
  BANKING_FINANCE_INSURANCE = 'BANKING_FINANCE_INSURANCE',

  REAL_ESTATE = 'REAL_ESTATE',

  OIL_AND_GAS = 'OIL_AND_GAS',

  HAULAGE_TRANSPORTATION = 'HAULAGE_TRANSPORTATION',

  HEALTH_HOSPITALITY = 'HEALTH_HOSPITALITY',

  DEFENCE_NATIONAL_SECURITY = 'DEFENCE_NATIONAL_SECURITY',

  COMMUNICATION = 'COMMUNICATION',

  TRANSPORTATION = 'TRANSPORTATION',

  HEALTH_EDUCATION = 'HEALTH_EDUCATION',

  AGRICULTURE = 'AGRICULTURE',

  INSTITUTIONS_COMMISSIONS_AUTHORITIES = 'INSTITUTIONS_COMMISSIONS_AUTHORITIES',

  PRIVATE_RESIDENCES_BUSINESSES = 'PRIVATE_RESIDENCES_BUSINESSES',

  RETAIL_DISTRIBUTION = 'RETAIL_DISTRIBUTION',
}
