export enum ServicePillar {
  BESPOKE_SOLUTIONS = 'BESPOKE_SOLUTIONS',

  DIGITAL_TRANSFORMATION = 'DIGITAL_TRANSFORMATION',

  CAPACITY_BUILDING = 'CAPACITY_BUILDING',

  ENTERPRISE_INTEGRATION = 'ENTERPRISE_INTEGRATION',

  CONSULTANCY = 'CONSULTANCY',
}
