package net.jojoaddison.consultancy.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LeadAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeadAllPropertiesEquals(Lead expected, Lead actual) {
        assertLeadAutoGeneratedPropertiesEquals(expected, actual);
        assertLeadAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeadAllUpdatablePropertiesEquals(Lead expected, Lead actual) {
        assertLeadUpdatableFieldsEquals(expected, actual);
        assertLeadUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeadAutoGeneratedPropertiesEquals(Lead expected, Lead actual) {
        assertThat(actual)
            .as("Verify Lead auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeadUpdatableFieldsEquals(Lead expected, Lead actual) {
        assertThat(actual)
            .as("Verify Lead relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getNeed()).as("check need").isEqualTo(expected.getNeed()))
            .satisfies(a -> assertThat(a.getMessage()).as("check message").isEqualTo(expected.getMessage()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeadUpdatableRelationshipsEquals(Lead expected, Lead actual) {
        // empty method
    }
}
