package net.jojoaddison.consultancy.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MilestoneAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMilestoneAllPropertiesEquals(Milestone expected, Milestone actual) {
        assertMilestoneAutoGeneratedPropertiesEquals(expected, actual);
        assertMilestoneAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMilestoneAllUpdatablePropertiesEquals(Milestone expected, Milestone actual) {
        assertMilestoneUpdatableFieldsEquals(expected, actual);
        assertMilestoneUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMilestoneAutoGeneratedPropertiesEquals(Milestone expected, Milestone actual) {
        assertThat(actual)
            .as("Verify Milestone auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMilestoneUpdatableFieldsEquals(Milestone expected, Milestone actual) {
        assertThat(actual)
            .as("Verify Milestone relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getState()).as("check state").isEqualTo(expected.getState()))
            .satisfies(a -> assertThat(a.getPosition()).as("check position").isEqualTo(expected.getPosition()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMilestoneUpdatableRelationshipsEquals(Milestone expected, Milestone actual) {
        assertThat(actual)
            .as("Verify Milestone relationships")
            .satisfies(a -> assertThat(a.getProject()).as("check project").isEqualTo(expected.getProject()));
    }
}
