package net.jojoaddison.consultancy.domain;

import static net.jojoaddison.consultancy.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ServiceItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceItemAllPropertiesEquals(ServiceItem expected, ServiceItem actual) {
        assertServiceItemAutoGeneratedPropertiesEquals(expected, actual);
        assertServiceItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceItemAllUpdatablePropertiesEquals(ServiceItem expected, ServiceItem actual) {
        assertServiceItemUpdatableFieldsEquals(expected, actual);
        assertServiceItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceItemAutoGeneratedPropertiesEquals(ServiceItem expected, ServiceItem actual) {
        assertThat(actual)
            .as("Verify ServiceItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceItemUpdatableFieldsEquals(ServiceItem expected, ServiceItem actual) {
        assertThat(actual)
            .as("Verify ServiceItem relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getRate()).as("check rate").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getRate()))
            .satisfies(a -> assertThat(a.getUnit()).as("check unit").isEqualTo(expected.getUnit()))
            .satisfies(a -> assertThat(a.getServiceGroup()).as("check serviceGroup").isEqualTo(expected.getServiceGroup()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceItemUpdatableRelationshipsEquals(ServiceItem expected, ServiceItem actual) {
        // empty method
    }
}
